-- +goose Up

ALTER TABLE warehouse_items
    ADD COLUMN IF NOT EXISTS item_obj_id INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS charge_count SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS durability SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS attr_enchant_kind SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS attr_enchant_level SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS inn_key_id INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS inn_npc_id INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS inn_hall BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS inn_due_time BIGINT NOT NULL DEFAULT 0;

-- +goose Down

ALTER TABLE warehouse_items
    DROP COLUMN IF EXISTS inn_due_time,
    DROP COLUMN IF EXISTS inn_hall,
    DROP COLUMN IF EXISTS inn_npc_id,
    DROP COLUMN IF EXISTS inn_key_id,
    DROP COLUMN IF EXISTS attr_enchant_level,
    DROP COLUMN IF EXISTS attr_enchant_kind,
    DROP COLUMN IF EXISTS durability,
    DROP COLUMN IF EXISTS charge_count,
    DROP COLUMN IF EXISTS item_obj_id;
