package packet

// ---------- Server Opcodes (V381) ----------

const (
	S_OPCODE_INITPACKET             byte = 150 // Init handshake (internal)
	S_OPCODE_DEPOSIT                byte = 4   // S_Deposit (open deposit window)
	S_OPCODE_ADD_INVENTORY_BATCH    byte = 5   // S_InvList
	S_OPCODE_DELETE_CHAR_OK         byte = 6
	S_OPCODE_STATUS                 byte = 8 // S_OwnCharStatus
	S_OPCODE_MOVE_OBJECT            byte = 10
	S_OPCODE_TRUETARGET             byte = 11 // S_TrueTarget
	S_OPCODE_ADD_ITEM               byte = 15 // S_AddItem (single item add)
	S_OPCODE_SOUND_EFFECT           byte = 22
	S_OPCODE_SKILL_BUY              byte = 23 // S_SkillBuy (magic shop list)
	S_OPCODE_CHANGE_ITEM_USE        byte = 24 // S_ItemAmount (stack count update)
	S_OPCODE_ATTACK                 byte = 30
	S_OPCODE_MANA_POINT             byte = 33 // S_MPUpdate
	S_OPCODE_MAGIC_STATUS           byte = 37 // S_SPMR
	S_OPCODE_HYPERTEXT              byte = 39
	S_OPCODE_CHANGE_LIGHT           byte = 40
	S_OPCODE_RANGESKILLS            byte = 42 // S_RangeSkill
	S_OPCODE_EFFECT                 byte = 55 // S_SkillSoundGFX
	S_OPCODE_REMOVE_INVENTORY       byte = 57
	S_OPCODE_CHARSYNACK             byte = 64 // 多用途: 裝備欄/盟徽/角色重置/角色資訊同步
	S_OPCODE_SHOP_SELL_LIST         byte = 65 // Items NPC buys from player
	S_OPCODE_SKILLBRAVE             byte = 67 // S_SkillBrave — brave/elf brave buff (2段加速效果)
	S_OPCODE_TELL                   byte = 73 // S_WhisperChat — whisper message
	S_OPCODE_SELL_LIST              byte = 70 // Items NPC sells to player
	S_OPCODE_MESSAGE_CODE           byte = 71 // S_ServerMsg
	S_OPCODE_SAY                    byte = 81
	S_OPCODE_RESURRECTION           byte = 85 // S_Resurrection
	S_OPCODE_PUT_OBJECT             byte = 87 // S_CharPack / S_OtherCharPack
	S_OPCODE_ADD_BOOKMARK           byte = 92
	S_OPCODE_CHARACTER_INFO         byte = 93 // S_CharPacks (char list)
	S_OPCODE_CREATE_CHARACTER_CHECK byte = 98
	S_OPCODE_CHANGE_ITEM_DESC       byte = 100 // S_ItemName
	S_OPCODE_DRUNKEN                byte = 103
	S_OPCODE_EXP                    byte = 113
	S_OPCODE_WEATHER                byte = 115
	S_OPCODE_CHANGE_DESC            byte = 119 // S_CharVisualUpdate
	S_OPCODE_REMOVE_OBJECT          byte = 120
	S_OPCODE_TIME                   byte = 123 // S_GameTime
	S_OPCODE_NEW_CHAR_INFO          byte = 127
	S_OPCODE_VERSION_CHECK          byte = 139 // S_ServerVersion
	S_OPCODE_CHANGENAME             byte = 46  // S_ChangeName
	S_OPCODE_HOUSELIST              byte = 156 // S_AuctionBoard（盟屋拍賣公告欄列表）
	S_OPCODE_ACTION                 byte = 158 // S_DoActionGFX
	S_OPCODE_ADD_SPELL              byte = 164
	S_OPCODE_INVISIBLE              byte = 171
	S_OPCODE_ABILITY_SCORES         byte = 174 // S_OwnCharAttrDef
	S_OPCODE_NUM_CHARACTER          byte = 178 // S_CharAmount
	S_OPCODE_WORLD                  byte = 206 // S_MapID
	S_OPCODE_CHANGE_ATTR            byte = 209
	S_OPCODE_ENTER_WORLD_CHECK      byte = 223 // S_LoginToGame
	S_OPCODE_HIT_POINT              byte = 225 // S_HPUpdate
	S_OPCODE_KICK                   byte = 227 // S_Disconnect
	S_OPCODE_LOGIN_CHECK            byte = 233 // S_LoginResult
	S_OPCODE_MESSAGE                byte = 243 // S_GlobalChat
	S_OPCODE_EVENT                  byte = 250 // S_PacketBox
	S_OPCODE_HP_METER               byte = 237 // S_HPMeter (NPC HP bar)
	S_OPCODE_SELECT_TARGET          byte = 236 // S_SelectTarget (pet attack targeting)
	S_OPCODE_STRUP                  byte = 166 // S_Strup (STR buff icon)
	S_OPCODE_DEXUP                  byte = 188 // S_Dexup (DEX buff icon)
	S_OPCODE_SKILLICONSHIELD        byte = 216 // S_SkillIconShield (AC buff icon)
	S_OPCODE_SPEED                  byte = 255 // S_SkillHaste
	S_OPCODE_RETRIEVE_LIST          byte = 176 // S_RetrieveList (warehouse item list)
	S_OPCODE_TRADE                  byte = 52  // S_Trade
	S_OPCODE_TRADEADDITEM           byte = 35  // S_TradeAddItem
	S_OPCODE_TRADESTATUS            byte = 112 // S_TradeStatus
	S_OPCODE_CHANGEHEADING          byte = 122 // S_ChangeHeading
	S_OPCODE_YES_NO                 byte = 219 // S_Message_YN (yes/no dialog)
	S_OPCODE_IDENTIFYDESC           byte = 245 // S_IdentifyDesc
	S_OPCODE_LAWFUL                 byte = 34  // S_Lawful
	S_OPCODE_PINKNAME               byte = 60  // S_PinkName
	S_OPCODE_REDMESSAGE             byte = 105 // S_RedMessage (center screen red text)
	S_OPCODE_ITEMCOLOR              byte = 240 // S_ItemColor (bless/color update)
	S_OPCODE_CLANNAME               byte = 72  // S_ClanName (clan name display update)
	S_OPCODE_EMBLEM                 byte = 118 // S_Emblem (emblem data download)
	S_OPCODE_CHARTITLE              byte = 183 // S_CharTitle (player title update)
	S_OPCODE_CLANATTENTION          byte = 200 // S_ClanAttention (clan status change notify)
	S_OPCODE_POLY                   byte = 76  // S_ChangeShape (polymorph visual change)
	S_OPCODE_CURSEBLIND             byte = 47  // S_CurseBlind (致盲螢幕遮罩)
	S_OPCODE_POISON                 byte = 165 // S_Poison (中毒/凍結色調)
	S_OPCODE_PARALYSIS              byte = 202 // S_Paralysis (麻痺/暈眩/凍結/睡眠/傳送鎖定)
	S_OPCODE_SELECTLIST             byte = 83  // S_FixWeaponList (repair weapon list)
	S_OPCODE_INPUTAMOUNT            byte = 136 // S_HowManyMake (crafting quantity dialog)
	S_OPCODE_BOARD                  byte = 68  // S_Board (bulletin board post list)
	S_OPCODE_BOARDREAD              byte = 148 // S_BoardRead (bulletin board post content)
	S_OPCODE_MAIL                   byte = 186 // S_Mail (mail system)
	S_OPCODE_NPCSHOUT               byte = 161 // S_NpcChat / S_NpcChatShouting / S_SystemMessage（NPC 聊天 type=0/2/3）
	S_OPCODE_PRIVATESHOPLIST        byte = 140 // S_PrivateShop（個人商店商品清單）
	S_OPCODE_CLANMATCHING           byte = 0   // S_ClanMatching（血盟配對系統）
	S_OPCODE_HOUSEMAP               byte = 187 // S_HouseMap（住宅地圖顯示）
	S_OPCODE_EFFECTLOCATION         byte = 106 // S_EffectLocation（地點動畫效果，陷阱觸發等）
	S_OPCODE_CASTLEMASTER           byte = 69  // S_CastleMaster（城主皇冠標誌）
	S_OPCODE_TAXRATE                byte = 185 // S_TaxRate（稅率設定 UI）
	S_OPCODE_WAR                    byte = 84  // S_War（戰爭狀態訊息）
	S_OPCODE_WARTIME                byte = 231 // S_WarTime（攻城戰時間選擇）
	S_OPCODE_DRAWAL                 byte = 141 // S_Drawal（城堡寶庫領出視窗）
)

// ---------- Client Opcodes (V381) ----------

const (
	C_OPCODE_ASK_XCHG                byte = 2
	C_OPCODE_DELETE_BOOKMARK         byte = 3
	C_OPCODE_QUERY_BUDDY             byte = 4
	C_OPCODE_DUEL                    byte = 5
	C_OPCODE_USE_SPELL               byte = 6
	C_OPCODE_REQUEST_ROLL            byte = 7  // C_ChangeChar
	C_OPCODE_COMMON_CLICK            byte = 16 // C_CommonClick（回選角後客戶端請求角色列表）
	C_OPCODE_PLATE                   byte = 10
	C_OPCODE_HYPERTEXT_INPUT_RESULT  byte = 11
	C_OPCODE_WAREHOUSE_CONTROL       byte = 13
	C_OPCODE_VERSION                 byte = 14
	C_OPCODE_UPLOAD_EMBLEM           byte = 18
	C_OPCODE_TAX                     byte = 19
	C_OPCODE_PERSONAL_SHOP           byte = 20
	C_OPCODE_BOARD_LIST              byte = 23
	C_OPCODE_DROP                    byte = 25
	C_OPCODE_RETURN_SUMMON           byte = 26
	C_OPCODE_MOVE                    byte = 29
	C_OPCODE_LEAVE_PARTY             byte = 33
	C_OPCODE_DIALOG                  byte = 34
	C_OPCODE_ADD_XCHG                byte = 37
	C_OPCODE_SHOP                    byte = 38 // C_Shop — 開設/取消個人商店
	C_OPCODE_BUY_SPELL               byte = 39
	C_OPCODE_CHAT                    byte = 40
	C_OPCODE_OPEN                    byte = 41
	C_OPCODE_INVITE_PARTY_TARGET     byte = 43
	C_OPCODE_WITHDRAW                byte = 44
	C_OPCODE_GIVE                    byte = 45
	C_OPCODE_QUERY_PERSONAL_SHOP     byte = 47
	C_OPCODE_MARRIAGE                byte = 50
	C_OPCODE_CHECK_PK                byte = 51
	C_OPCODE_TELEPORT                byte = 52
	C_OPCODE_DEPOSIT                 byte = 56
	C_OPCODE_LEAVE_PLEDGE            byte = 61
	C_OPCODE_THROW                   byte = 62
	C_OPCODE_RANK_CONTROL            byte = 63
	C_OPCODE_WHO_PLEDGE              byte = 68
	C_OPCODE_BAN_MEMBER              byte = 69
	C_OPCODE_ACCEPT_XCHG             byte = 71
	C_OPCODE_ALT_ATTACK              byte = 72
	C_OPCODE_PLEDGE_WATCH            byte = 78
	C_OPCODE_CREATE_CUSTOM_CHARACTER byte = 84
	C_OPCODE_CANCEL_XCHG             byte = 86
	C_OPCODE_MAIL                    byte = 87
	C_OPCODE_TITLE                   byte = 90
	C_OPCODE_ALIVE                   byte = 95
	C_OPCODE_CHAR_RESET              byte = 98 // 角色重置（洗點）
	C_OPCODE_CHECK_INVENTORY         byte = 103
	C_OPCODE_NPC_ITEM_CONTROL        byte = 104
	C_OPCODE_GET                     byte = 112
	C_OPCODE_BOARD_READ              byte = 114
	C_OPCODE_FIX                     byte = 118
	C_OPCODE_LOGIN                   byte = 119
	C_OPCODE_ACTION                  byte = 120
	C_OPCODE_ATTR                    byte = 121 // C_Attr (S_Message_YN yes/no response)
	C_OPCODE_QUIT                    byte = 122
	C_OPCODE_FAR_ATTACK              byte = 123
	C_OPCODE_HACTION                 byte = 125
	C_OPCODE_MERCENARYARRANGE        byte = 129
	C_OPCODE_SAY                     byte = 136
	C_OPCODE_ENTER_WORLD             byte = 137
	C_OPCODE_DESTROY_ITEM            byte = 138
	C_OPCODE_BOARD_WRITE             byte = 141
	C_OPCODE_BUYABLE_SPELL           byte = 145
	C_OPCODE_BOARD_DELETE            byte = 153
	C_OPCODE_BUY_SELL                byte = 161
	C_OPCODE_DELETE_CHARACTER        byte = 162
	C_OPCODE_USE_ITEM                byte = 164
	C_OPCODE_BOOKMARK                byte = 165
	C_OPCODE_EXCLUDE                 byte = 171
	C_OPCODE_EXIT_GHOST              byte = 173
	C_OPCODE_RESTART                 byte = 177
	C_OPCODE_TELL                    byte = 184
	C_OPCODE_SUMMON                  byte = 185
	C_OPCODE_JOIN_PLEDGE             byte = 194
	C_OPCODE_CHAT_PARTY_CONTROL      byte = 199
	C_OPCODE_REMOVE_BUDDY            byte = 202
	C_OPCODE_WHO                     byte = 206
	C_OPCODE_ADD_BUDDY               byte = 207
	C_OPCODE_SHIFT_SERVER            byte = 210
	C_OPCODE_ENTER_PORTAL            byte = 219
	C_OPCODE_CREATE_PLEDGE           byte = 222
	C_OPCODE_SLAVE_CONTROL           byte = 223
	C_OPCODE_CHANGE_DIRECTION        byte = 225
	C_OPCODE_WAR                     byte = 227
	C_OPCODE_ATTACK                  byte = 229
	C_OPCODE_WHO_PARTY               byte = 230
	C_OPCODE_ENTER_SHIP              byte = 231
	C_OPCODE_SAVEIO                  byte = 244
	C_OPCODE_EXCHANGEABLE_SPELL      byte = 245
	C_OPCODE_SHUTDOWN                byte = 253
	C_OPCODE_WINDOWS                 byte = 254 // Java: C_Windows（書籤排序/地圖計時等）
	C_OPCODE_BANISH_PARTY            byte = 255
	C_OPCODE_CLAN_MATCHING           byte = 76 // C_ClanMatching / C_ClanRecommend（血盟配對系統）
)
